### ISSUE TITLE
There is no response from the agent.

### ISSUE THREAD

**Issue by utkubagdas** [inworld-ai/inworld-unity-sdk#77] opened 2023-06-21 06:21 UTC
Hello, I am creating characters in runtime as you mentioned in the your documentation in my project. It comes to the console successfully in all logs, all connections seem to be ok, I can even write a message to the agent, but his response is not coming from the sdk. but when i look at inworld studio the agent actually replied to me but unity sdk is not getting this message. why, can you help? Thanks.

My Instantiate code:

```
public void CreateCharacter(GameObject newCharacter, Vector3 spawnPos, bool isFirst)
        {
            if (m_CurrentCharacter)
                Destroy(m_CurrentCharacter.gameObject);
            var characterGameObject = Instantiate(newCharacter, spawnPos, Quaternion.identity);
            var inWorldCharacter = characterGameObject.GetComponentInChildren<InworldCharacter>();
            m_CurrentCharacter = inWorldCharacter;
            Player = characterGameObject;
            if (!isFirst)
            {
                inWorldCharacter.RegisterLiveSession();
            }
        }
```

<img width="120" alt="inworld1" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/cc399190-b8d0-48ed-baeb-a71e3b72f665">

<img width="302" alt="inworld2" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/7eb21abd-0698-4346-b74d-28cdf6d071df">

![inworld3](https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/2d86d456-254f-45f8-933b-7569ad63b62c)

**Comment by utkubagdas** [comment] 2023-06-21 12:50
I tried to fix it but now it gives this error when I send message.
Error: Exception: chatmate:5ede3a61-0576-49fe-81b1-55e64c506a49: Status(StatusCode="NotFound", Detail="Character with id: '41a17819-4f77-4c19-9f3f-d2fbfd98c4b0' was not loaded. Ensure to use correct ids from LoadScene results.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1687351686.354803000","description":"Error received from peer ipv4:34.120.166.226:443","file":"/Users/miki/Documents/grpc/src/src/core/lib/surface/call.cc","file_line":905,"grpc_message":"Character with id: '41a17819-4f77-4c19-9f3f-d2fbfd98c4b0' was not loaded. Ensure to use correct ids from LoadScene results.","grpc_status":5}")

**Comment by Div-Inworld** [comment] 2023-06-22 17:06
> 

Hi, it seems like your character has possibly been corrupted. are you able to log out via the Inworld Studio Panel and back in to see if it cleans it?

**Comment by utkubagdas** [comment] 2023-06-23 10:10
There doesn't seem to be a problem in inworld studio. I reinstalled the inworld sdk in Unity. I logged in. And as you said in the documentation, I try to create the character, this time the inworld connects, but when the character is created, the character does not connect and gives some errors.

these codes are inside the InworldController.

I am calling this method from outside another class.

My characters and inworld controller hierarchy is the same as your demo scene.

`  public void CreateCharacter(InworldCharacter inWorldCharacter)
        {
            if (m_CurrentCharacter)
                Destroy(m_CurrentCharacter.gameObject);
            m_CurrentCharacter = Instantiate(inWorldCharacter, transform);
            m_CurrentCharacter.RegisterLiveSession();
        }`

After unity start;

<img width="1021" alt="iw1" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/73a36789-c425-49b4-9106-e7e0ef4ba38a">

after character create is called; The character prefab is created and no connection is established with the character.
Console outputs;

<img width="1025" alt="iw2" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/4421dc8c-5566-45e7-bcb9-7f87ec986bbf">

<img width="950" alt="iw4" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/38994661/687c1fa0-14c3-4453-bc63-85ab15943fbd">

Can u help me? Thanks!

**Comment by Juniverse** [comment] 2023-07-26 16:25
Hello @utkubagdas ,

The issue is probably becasue when you are calling `RegisterLiveSession`, the LoadScene hasn't finished yet so the Live session hasn't been started. So the ID is still from the old session

**Comment by Div-Inworld** [comment] 2023-07-26 19:58
> There doesn't seem to be a problem in inworld studio. I reinstalled the inworld sdk in Unity. I logged in. And as you said in the documentation, I try to create the character, this time the inworld connects, but when the character is created, the character does not connect and gives some errors.
> 
> these codes are inside the InworldController.
> 
> I am calling this method from outside another class.
> 
> My characters and inworld controller hierarchy is the same as your demo scene.
> 
> ` public void CreateCharacter(InworldCharacter inWorldCharacter) { if (m_CurrentCharacter) Destroy(m_CurrentCharacter.gameObject); m_CurrentCharacter = Instantiate(inWorldCharacter, transform); m_CurrentCharacter.RegisterLiveSession(); }`
> 
> After unity start;
> 
> <img alt="iw1" width="1021" src="https://user-images.githubusercontent.com/38994661/248239414-73a36789-c425-49b4-9106-e7e0ef4ba38a.png">
> after character create is called; The character prefab is created and no connection is established with the character. Console outputs;
> 
> <img alt="iw2" width="1025" src="https://user-images.githubusercontent.com/38994661/248239975-4421dc8c-5566-45e7-bcb9-7f87ec986bbf.png"> <img alt="iw4" width="950" src="https://user-images.githubusercontent.com/38994661/248240131-687c1fa0-14c3-4453-bc63-85ab15943fbd.png">
> Can u help me? Thanks!

Hi @utkubagdas 

This PR has the FIx. Once it is merged in you should be able to use the latest and be good to go!
https://github.com/inworld-ai/inworld-unity-sdk/pull/78

**Closed by Div-Inworld** 2023-07-26 19:58 UTC
